// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXADpvFUtW1cdztAQLvDkCuvpgSFSzJI',
    appId: '1:845233473907:web:4160055aaa8bd6da161d06',
    messagingSenderId: '845233473907',
    projectId: 'firebase-final-simplethreads',
    authDomain: 'fir-final-simplethreads.firebaseapp.com',
    storageBucket: 'firebase-final-simplethreads.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW74llpangnitJLLeJKRNYq1Izu8QyurU',
    appId: '1:845233473907:android:2cdfac04d8ca5e6b161d06',
    messagingSenderId: '845233473907',
    projectId: 'firebase-final-simplethreads',
    storageBucket: 'firebase-final-simplethreads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMUgB7BZ3UsusUstBnmKFfZ1N36Uy6Zn8',
    appId: '1:845233473907:ios:6cac3f13c71f3fba161d06',
    messagingSenderId: '845233473907',
    projectId: 'firebase-final-simplethreads',
    storageBucket: 'firebase-final-simplethreads.appspot.com',
    iosBundleId: 'com.example.firebaseFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMUgB7BZ3UsusUstBnmKFfZ1N36Uy6Zn8',
    appId: '1:845233473907:ios:35d5ee2310447a20161d06',
    messagingSenderId: '845233473907',
    projectId: 'firebase-final-simplethreads',
    storageBucket: 'firebase-final-simplethreads.appspot.com',
    iosBundleId: 'come.example.applethreads',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLXADpvFUtW1cdztAQLvDkCuvpgSFSzJI',
    appId: '1:845233473907:web:2dfa42f0547f3ca8161d06',
    messagingSenderId: '845233473907',
    projectId: 'firebase-final-simplethreads',
    authDomain: 'fir-final-simplethreads.firebaseapp.com',
    storageBucket: 'firebase-final-simplethreads.appspot.com',
  );
}
